### ISSUE TITLE
crypto: Inspect key type and make sure the OnceCell bytes are dealt with properly 

### ISSUE THREAD

**Issue by joyqvq** [MystenLabs/fastcrypto#16]
Yes, it lets us set up the [binary representation manifest](https://github.com/zefchain/serde-reflection) for our project. In fact, this makes me think we should open an issue to inspect the key types and use serde annotations to make sure the `OnceCell` is elided when serializing, and reset when deserializing. We should open an issue.

_Originally posted by @huitseeker in https://github.com/MystenLabs/narwhal/pull/624#discussion_r936630718_

**Comment by jonas-lj** [comment]
If I've understood this correctly, we need to ensure the following:
1) Structs containing cryptographic material which has a non-trivial `as_ref`/`to_bytes` function stores the result in a `OnceCell` the first time it's called and uses this for later calls,
2) The content of OnceCell is not accidentally included when serializing,
3) When deserializing, the OnceCell field is reset.

I've checked this for
* BLS public keys, private keys, signatures and aggregate signatures, all OK,
* Pedersen commitments (note that here, the serialization are the same as `as_ref`)
* Ed25519 signatures ok. Serialization has custom implementation. Ed25519 private key is already binary, and the public key is an encoding of a point but uses the underlying crates `to_bytes` function to implement `as_ref`.
* Secp256k1 public keys, private keys and signatures all has a OnceCell field, but serialization is handled by custom implementations. OK
* AES does not have any OnceCell since keys are already binary.

So it looks fine for now, but we need to remember to do this for future schemes we include in fastcrypto.
