### ISSUE TITLE
[secpr1] Explore optimizations on ECDSA R1

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#295]
Atm ECDSA R1 verification is by far more expensive than ECDSA K1, see: https://github.com/MystenLabs/fastcrypto/issues/185#issuecomment-1346127493

Indeed, Bitcoin's C library for K1 seems to be one of the fastest in the space so we should explore if the same should happen for R1 too (ie by forking the above C lib) or use a different Rust crate than the one we rely on today or change the backend to fiatcrypto?

**Comment by jonas-lj** [comment]
It turns out that `p256` does not implement optimised linear combinations. However, it is [implemented](https://github.com/RustCrypto/elliptic-curves/blob/5a43e666f1c73cfe05c4a687c295312d51cee1d6/k256/src/arithmetic/mul.rs#L313) in the `k256`, so with a bit of effort we could make a similar implementation for `p256`.

**Comment by jonas-lj** [comment]
#566 was a step forward and next steps will be considered in another issue: https://github.com/MystenLabs/fastcrypto/issues/573.
