### ISSUE TITLE
Ensure final check of dep updates

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#527]
Especially those related to functionality used by Sui.

**Comment by jonas-lj** [comment]
As of revision 74e007a945d69a7dc89c642e544f01c5fb648a41, the following dependencies could be updated (output from `cargo updgrades`):
```
	ecdsa matches 0.15.1;	latest is 0.16.1
	elliptic-curve matches 0.12.3;	latest is 0.13.2
	p256 matches 0.12.0;	latest is 0.13.0
	rfc6979 matches 0.3.1;	latest is 0.4.0
	secp256k1 matches 0.26.0;	latest is 0.27.0
	signature matches 1.6.4;	latest is 2.0.0
	k256 matches 0.11.6;	latest is 0.13.0
	wycheproof matches 0.4.0;	latest is 0.5.0
```
The `p256`, `ecdsa`, `rfc6979` and `signature` crates are handled by https://github.com/MystenLabs/fastcrypto/pull/516, so that leaves `elliptic-curve` and `secp256k1` since the last two are only dev-depenedencies.
